CREATE DATABASE IF NOT EXISTS tsprod 
	DEFAULT CHARACTER SET = 'utf8' 
	DEFAULT COLLATE = 'utf8_general_ci';

CREATE TABLE `city` (
    `CITYID` INT(6) UNSIGNED NOT NULL,
    `NAME` VARCHAR(99),
    `SIZE` INT(6) UNSIGNED,
    PRIMARY KEY (`CITYID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

insert into city (cityid, name, size) values (0, "", 0);

CREATE TABLE `council` (
    `COUNCILID` INT(6) UNSIGNED NOT NULL,
    `CITYID` INT(6) UNSIGNED,
    `NAME` VARCHAR(99),
    `KEEPER` VARCHAR(99),
    `JOB` VARCHAR(99),
    `RACE` VARCHAR(99),
    `SKILL` VARCHAR(99),
    `ALLIES` INT(6) UNSIGNED,
    `ENEMIES` INT(6) UNSIGNED,
    `INFLUENCE` INT(6) UNSIGNED,
    PRIMARY KEY (`COUNCILID`),
    KEY `CITYID` (`CITYID`),
    CONSTRAINT `council_fk1` FOREIGN KEY (`CITYID`) REFERENCES `city` (`CITYID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

insert into council (councilid, cityid, name, keeper, job, race, skill, allies, enemies, influence) values (0, 0, "", "", "", "", "", 0, 0, 0);

CREATE TABLE `guild` (
    `GUILDID` INT(6) UNSIGNED NOT NULL,
    `NAME` VARCHAR(99),
    `SIZE` INT(6) UNSIGNED,
    PRIMARY KEY (`GUILDID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

insert into guild (guildid, name, size) values (0, "", 0);

--SUBSCRIBER = 0 - not a subscriber
--SUBSCRIBER = 1 - is a subscriber
--ISPOLITICALLYACTIVE = 0 - not active
--ISPOLITICALLYACTIVE = 1 - is active
CREATE TABLE `hero` (
    `HEROID` INT(6) UNSIGNED NOT NULL,
    `CITYID` INT(6) UNSIGNED NULL DEFAULT 0,
    `NAME` VARCHAR(99),
    `KEEPER` VARCHAR(99),
    `GUILDID` INT(6) UNSIGNED,
    `ALLY` INT(6) UNSIGNED NULL,
    `ENEMY` INT(6) UNSIGNED NULL,
    `SUBSCRIBER` INT(6) UNSIGNED NULL DEFAULT 0,
    `LASTVISITTIMESTAMP` INT(6) UNSIGNED NULL,
    `ISPOLITICALLYACTIVE` INT(6) UNSIGNED NULL,
    `LEVEL` INT(6) UNSIGNED NULL,
    PRIMARY KEY (`HEROID`),
    KEY `CITYID` (`CITYID`),
    CONSTRAINT `hero_fk1` FOREIGN KEY (`CITYID`) REFERENCES `city` (`CITYID`),
    CONSTRAINT `hero_fk2` FOREIGN KEY (`GUILDID`) REFERENCES `guild` (`GUILDID`),
    CONSTRAINT `hero_fk3` FOREIGN KEY (`ALLY`) REFERENCES `council` (`COUNCILID`),
    CONSTRAINT `hero_fk4` FOREIGN KEY (`ENEMY`) REFERENCES `council` (`COUNCILID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `vote` (
    `VOTEID` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
    `CITYID` INT(6) UNSIGNED NOT NULL,
    `HEROID` INT(6) UNSIGNED NOT NULL,
    PRIMARY KEY (`VOTEID`),
    CONSTRAINT `vote_fk1` FOREIGN KEY (`CITYID`) REFERENCES `city` (`CITYID`),
    CONSTRAINT `vote_fk2` FOREIGN KEY (`HEROID`) REFERENCES `hero` (`HEROID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `scheduler` (
	`RUNNING` INT(6) UNSIGNED NOT NULL)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;