CREATE TABLE `strategy` (
    `ID` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
    `TYPE` VARCHAR(20) NOT NULL,
    `NAME` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=8;

CREATE TABLE `city` (
    `CITYID` INT(6) UNSIGNED NOT NULL,
    `NAME` VARCHAR(20),
    `SIZE` INT(6) UNSIGNED,
    PRIMARY KEY (`CITYID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `council` (
    `COUNCILID` INT(6) UNSIGNED NOT NULL,
    `CITYID` INT(6) UNSIGNED,
    `NAME` VARCHAR(20),
    `JOB` VARCHAR(20),
    `RACE` VARCHAR(20),
    `SKILL` VARCHAR(20),
    `ALLIES` INT(6) UNSIGNED,
    `ENEMIES` INT(6) UNSIGNED,
    PRIMARY KEY (`COUNCILID`),
    KEY `CITYID` (`CITYID`),
    CONSTRAINT `council_fk1` FOREIGN KEY (`CITYID`) REFERENCES `city` (`CITYID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `hero` (
    `HEROID` INT(6) UNSIGNED NOT NULL,
    `CITYID` INT(6) UNSIGNED,
    `NAME` VARCHAR(20),
    `GUILDID` INT(6) UNSIGNED,
    `ALLY` INT(6) UNSIGNED,
    `ENEMY` INT(6) UNSIGNED,
    PRIMARY KEY (`HEROID`),
    KEY `CITYID` (`CITYID`),
    CONSTRAINT `hero_fk1` FOREIGN KEY (`CITYID`) REFERENCES `city` (`CITYID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;